### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by gibmat** [dustinkirkland/golang-petname#12]
Please tag releases of this library that correspond to the versions you list in `debian/changelog`. Doing so will greatly help individuals who are packaging this library and using something like a watchfile to track new releases.

(I'm working on updating Debian's version of this package, and due to a historical decision about the versioning of Debian's packaging, Debian's version is a mashup of `<version>+<git commit>`. Proper tagging would eliminate this less than ideal situation.)

**Comment by dustinkirkland** [comment]
Sure, sorry about that.  Will do that going forward.  I'm in the process of moving from Launchpad/bzr to Github/git right now and will update the release scripts accordingly.  Thanks for your help packaging this for Debian!
