### ISSUE TITLE
Consider allow older versions of Go

### ISSUE THREAD

**Issue by stgraber** [dustinkirkland/golang-petname#18]
For Incus (ex-LXD), we like supporting the past two major Go versions, that is, 1.20 and 1.21 currently.

Your recent change to introduce a `go.mod` came with you setting a minimal version of `go 1.21.1` which is therefore breaking us.

I don't see any reason for petname to require 1.21.1, so you should be able to just `go mod tidy --go=1.20` to set the base version to 1.20.

**Comment by dustinkirkland** [comment]
Sure thing, no problem!  Fixed.
